<?php

return [

    'cache' => [
        'ttl' => [
            'admin'   => 60,   // seconds
            'creator' => 120,
            'system'  => 30,
        ],
    ],

    'periods' => [
        'today', 'yesterday', 'last_7_days',
        'current_week', 'previous_week',
        'current_month', 'previous_month', 'last_30_days',
        'current_quarter', 'last_90_days',
        'current_year', 'previous_year',
    ],

    // The three periods surfaced as primary UI options for all tools.
    'primary_periods' => ['today', 'current_week', 'current_month'],

    'tools' => [
        'get_post_overview' => [
            'class'           => \App\Services\Analytics\Tools\PostOverviewTool::class,
            'description'     => 'Post count by status (published, hidden, draft, scheduled). Growth vs comparison period.',
            'scopes'          => ['creator', 'admin'],
            'subjects'        => ['self', 'platform', 'specific_user'],
            'admin_only'      => false,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => ['status', 'creator_id', 'content_type'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters', 'user_id', 'limit'],
            'metrics'         => ['total_posts', 'published_posts', 'hidden_posts', 'scheduled_posts', 'draft_posts', 'audience_breakdown', 'items', 'change_pct'],
        ],

        'get_post_engagement_breakdown' => [
            'class'           => \App\Services\Analytics\Tools\PostEngagementBreakdownTool::class,
            'description'     => 'Total views, likes, comments, shares, bookmarks. Engagement rate per post.',
            'scopes'          => ['creator', 'admin'],
            'subjects'        => ['self', 'platform', 'specific_user'],
            'admin_only'      => false,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => ['creator_id', 'content_type', 'status'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters', 'user_id'],
            'metrics'         => ['total_views', 'total_likes', 'total_comments', 'total_shares', 'total_bookmarks', 'engagement_rate', 'by_type_breakdown'],
        ],

        'get_post_status_breakdown' => [
            'class'           => \App\Services\Analytics\Tools\PostStatusBreakdownTool::class,
            'description'     => 'Break posts down by status: published/hidden/draft/scheduled/deleted.',
            'scopes'          => ['creator', 'admin'],
            'subjects'        => ['self', 'platform', 'specific_user'],
            'admin_only'      => false,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => ['status', 'creator_id'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters', 'user_id'],
            'metrics'         => ['status_breakdown'],
        ],

        'get_follower_growth' => [
            'class'           => \App\Services\Analytics\Tools\FollowerGrowthTool::class,
            'description'     => 'Follower count, new followers gained, unfollows, net growth in period.',
            'scopes'          => ['creator'],
            'subjects'        => ['self'],
            'admin_only'      => false,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => [],
            'required_params' => ['period'],
            'optional_params' => ['compare_with'],
            'metrics'         => ['total_followers', 'new_followers', 'net_growth', 'change_pct'],
        ],

        'get_account_overview' => [
            'class'           => \App\Services\Analytics\Tools\AccountOverviewTool::class,
            'description'     => 'Personal account overview: profile, verification, followers, following, total posts, and period activity.',
            'scopes'          => ['creator'],
            'subjects'        => ['self'],
            'admin_only'      => false,
            'cacheable'       => true,
            'default_period'  => 'current_month',
            'allowed_filters' => [],
            'required_params' => ['period'],
            'optional_params' => ['compare_with'],
            'metrics'         => ['username', 'name', 'followers_count', 'following_count', 'total_posts', 'period_posts', 'is_verified', 'is_banned'],
        ],

        'get_screen_time_overview' => [
            'class'           => \App\Services\Analytics\Tools\ScreenTimeOverviewTool::class,
            'description'     => 'Session duration, video watch time ratio, daily usage trend, peak hour. Use for wellness, screen time, usage analysis.',
            'scopes'          => ['creator'],
            'subjects'        => ['self'],
            'admin_only'      => false,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => [],
            'required_params' => ['period'],
            'optional_params' => ['compare_with'],
            'metrics'         => ['avg_session_duration', 'total_screen_time', 'video_watch_ratio', 'daily_series', 'peak_hour', 'activity_breakdown'],
        ],

        'get_top_videos' => [
            'class'           => \App\Services\Analytics\Tools\TopVideosTool::class,
            'description'     => 'Top videos ranked by views, likes, comments, shares, watch time, or engagement rate.',
            'scopes'          => ['creator', 'admin'],
            'subjects'        => ['self', 'platform', 'specific_user'],
            'admin_only'      => false,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => ['sort_by', 'creator_id', 'status'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters', 'limit', 'user_id'],
            'metrics'         => ['video_id', 'title', 'views', 'likes', 'comments', 'shares', 'engagement_rate'],
        ],

        'get_comment_overview' => [
            'class'           => \App\Services\Analytics\Tools\CommentOverviewTool::class,
            'description'     => 'Total comments and comment growth. Comments are stored as posts with type=comment.',
            'scopes'          => ['creator', 'admin'],
            'subjects'        => ['self', 'platform', 'specific_user'],
            'admin_only'      => false,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => ['creator_id', 'status'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters', 'user_id', 'limit'],
            'metrics'         => ['total_comments', 'comment_growth', 'items', 'change_pct'],
        ],

        'get_ai_studio_metrics' => [
            'class'           => \App\Services\Analytics\Tools\AiStudioMetricsTool::class,
            'description'     => 'AI Studio token usage, cost (USD), success rate, intent breakdown, daily cost series.',
            'scopes'          => ['creator', 'admin'],
            'subjects'        => ['self', 'platform'],
            'admin_only'      => false,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => ['intent', 'status'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters'],
            'metrics'         => ['total_tokens', 'total_cost_usd', 'total_requests', 'success_rate', 'intent_breakdown', 'daily_series'],
        ],

        'get_scheduled_post_metrics' => [
            'class'           => \App\Services\Analytics\Tools\ScheduledPostMetricsTool::class,
            'description'     => 'Scheduled post counts, publish success rate, avg delay, source breakdown (manual/calendar).',
            'scopes'          => ['creator', 'admin'],
            'subjects'        => ['self', 'platform'],
            'admin_only'      => false,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => ['status', 'source'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters'],
            'metrics'         => ['scheduled_total', 'published', 'failed', 'cancelled', 'success_rate', 'avg_delay_minutes', 'source_breakdown'],
        ],

        /**
         * Admin Analytics Tools - these require admin scopes and are focused on platform-wide insights,
         * user behavior, content moderation, and system health.
         * They often include more sensitive data and may have stricter caching policies to balance performance
         *  with data freshness.
         */

        'get_user_growth' => [
            'class'           => \App\Services\Analytics\Tools\UserGrowthTool::class,
            'description'     => 'Platform-wide user growth, new users, active users, ban rate, daily trend.',
            'scopes'          => ['admin'],
            'subjects'        => ['platform'],
            'admin_only'      => true,
            'cacheable'       => true,
            'default_period'  => 'current_month',
            'allowed_filters' => ['role', 'status', 'country'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters', 'limit'],
            'metrics'         => ['total_users', 'new_users', 'banned_users', 'verified_users', 'temp_ban_count', 'perm_ban_count', 'daily_series', 'items', 'change_pct'],
        ],

        'get_active_user_trend' => [
            'class'           => \App\Services\Analytics\Tools\ActiveUserTrendTool::class,
            'description'     => 'Daily and weekly active users trend over the period.',
            'scopes'          => ['admin'],
            'subjects'        => ['platform'],
            'admin_only'      => true,
            'cacheable'       => true,
            'default_period'  => 'current_month',
            'allowed_filters' => ['role'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters'],
            'metrics'         => ['dau_series', 'wau_series', 'change_pct'],
        ],

        'get_appeal_overview' => [
            'class'           => \App\Services\Analytics\Tools\AppealOverviewTool::class,
            'description'     => 'Appeal counts: total, approved, rejected, pending, approval rate, breakdown by type.',
            'scopes'          => ['admin'],
            'subjects'        => ['platform', 'specific_user', 'specific_post', 'specific_video'],
            'admin_only'      => true,
            'cacheable'       => true,
            'default_period'  => 'current_month',
            'allowed_filters' => ['appeal_status', 'resource_type', 'creator_id', 'post_id', 'video_id'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters', 'limit'],
            'metrics'         => ['total_appeals', 'approved', 'rejected', 'pending', 'approval_rate', 'items'],
        ],

        'get_appeal_sla_metrics' => [
            'class'           => \App\Services\Analytics\Tools\AppealSlaTool::class,
            'description'     => 'Appeal SLA: oldest pending age in days, average resolution time, backlog alerts.',
            'scopes'          => ['admin'],
            'subjects'        => ['platform'],
            'admin_only'      => true,
            'cacheable'       => true,
            'default_period'  => 'current_month',
            'allowed_filters' => ['appeal_status', 'resource_type'],
            'required_params' => ['period'],
            'optional_params' => ['filters'],
            'metrics'         => ['oldest_pending_days', 'avg_resolution_hours', 'pending_count', 'by_type'],
        ],

        'get_ai_copilot_metrics' => [
            'class'           => \App\Services\Analytics\Tools\AiCopilotMetricsTool::class,
            'description'     => 'AI Copilot session/message stats, top intents, top users by token cost.',
            'scopes'          => ['admin'],
            'subjects'        => ['platform'],
            'admin_only'      => true,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => ['intent', 'status'],
            'required_params' => ['period'],
            'optional_params' => ['compare_with', 'filters'],
            'metrics'         => ['total_requests', 'top_intents', 'top_users_by_cost', 'daily_series'],
        ],

        'get_top_creators' => [
            'class'           => \App\Services\Analytics\Tools\TopCreatorsTool::class,
            'description'     => 'Top creators ranked by followers, views, posts, or engagement.',
            'scopes'          => ['admin'],
            'subjects'        => ['platform'],
            'admin_only'      => true,
            'cacheable'       => true,
            'default_period'  => 'current_month',
            'allowed_filters' => ['sort_by'],
            'required_params' => ['period'],
            'optional_params' => ['filters', 'limit'],
            'metrics'         => ['creator_id', 'username', 'followers', 'views', 'posts', 'avg_engagement_rate'],
        ],

        'get_admin_audit_logs' => [
            'class'           => \App\Services\Analytics\Tools\AdminAuditLogsTool::class,
            'description'     => 'Admin action counts by type (ban, unban, delete post, approve appeal, etc.) in period.',
            'scopes'          => ['admin'],
            'subjects'        => ['platform'],
            'admin_only'      => true,
            'cacheable'       => true,
            'default_period'  => 'current_week',
            'allowed_filters' => ['action_type', 'admin_id', 'resource_type'],
            'required_params' => ['period'],
            'optional_params' => ['filters', 'limit'],
            'metrics'         => ['total_actions', 'action_breakdown', 'top_admins', 'resource_breakdown', 'items'],
        ],


        'get_system_health' => [
            'class'           => \App\Services\Analytics\Tools\SystemHealthTool::class,
            'description'     => 'Overall system health: pending appeals, failed encodings, active queue, AI success rate.',
            'scopes'          => ['admin', 'system'],
            'subjects'        => ['platform'],
            'admin_only'      => true,
            'cacheable'       => true,
            'default_period'  => 'today',
            'allowed_filters' => [],
            'required_params' => ['period'],
            'optional_params' => [],
            'metrics'         => ['pending_appeals', 'failed_encodings', 'active_queue', 'ai_success_rate'],
        ],

        'get_encoding_queue_status' => [
            'class'           => \App\Services\Analytics\Tools\EncodingQueueStatusTool::class,
            'description'     => 'Video encoding queue: pending, processing, failed, stuck jobs, avg processing time.',
            'scopes'          => ['admin', 'system'],
            'subjects'        => ['platform'],
            'admin_only'      => true,
            'cacheable'       => true,
            'default_period'  => 'today',
            'allowed_filters' => ['status', 'resolution', 'error_type'],
            'required_params' => ['period'],
            'optional_params' => ['filters', 'limit'],
            'metrics'         => ['pending_jobs', 'processing_jobs', 'failed_jobs', 'stuck_jobs', 'avg_processing_time', 'error_summary', 'items'],
        ],

        'get_queue_failure_stats' => [
            'class'           => \App\Services\Analytics\Tools\QueueFailureTool::class,
            'description'     => 'Laravel queue job failures: total failed, by queue name, top failure messages.',
            'scopes'          => ['admin', 'system'],
            'subjects'        => ['platform'],
            'admin_only'      => true,
            'cacheable'       => true,
            'default_period'  => 'today',
            'allowed_filters' => ['queue_name', 'job_class'],
            'required_params' => ['period'],
            'optional_params' => ['filters'],
            'metrics'         => ['total_failed_jobs', 'by_queue', 'top_error_messages'],
        ],

    ],

];
