import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import localFont from "next/font/local";

export const tiktokFont = localFont({
    src: [
        {
            path: "../assets/fonts/TikTokFont-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../assets/fonts/TikTokFont-Semibold.woff2",
            weight: "600",
            style: "normal",
        },
        {
            path: "../assets/fonts/TikTokFont-Bold.woff2",
            weight: "700",
            style: "normal",
        },
    ],
    display: "swap",
    variable: "--font-tiktok",
});

export const tiktokDisplayFont = localFont({
    src: [
        {
            path: "../assets/fonts/TikTokDisplayFont-Bold.woff2",
            weight: "700",
            style: "normal",
        },
    ],
    display: "swap",
    variable: "--font-tiktok-display",
});

export const metadata: Metadata = {
    title: "Tiktok",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${tiktokDisplayFont.variable} ${tiktokFont.variable} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
